// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dummy.sql

package querier

import (
	"context"
)

const dummyQuery = `-- name: DummyQuery :one
SELECT 1::BIGINT
`

func (q *Queries) DummyQuery(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, dummyQuery)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
