name: pr-code-check

on:
  pull_request:
    branches:
      - main
      - release-**

jobs:
  code-check:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    - name: Codegen Check
      shell: bash
      run: make codegen-check
    - name: Lint Check
      shell: bash
      run: make lint-check
    - name: Unit Tests
      shell: bash
      run: make ut
